name: label pull request

on:
  workflow_call:

jobs:
  check_labeler_matches:
    name: check labeler matches
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request based on paths of changed files
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b
        with:
          dot: true
