name: tag if missing

on:
  workflow_call:
    inputs:
      toolbox_envy_bins:
        description: Toolbox Envy bin namespaces
        required: true
        type: string
    secrets:
      APP_ID:
        description: GitHub App installation ID
        required: true
      APP_PRIVATE_KEY:
        description: GitHub App private key
        required: true

jobs:
  tag_if_missing:
    name: tag if missing
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        name: Generate a GitHub App token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git identity
        run: |
          git config user.name "senile-errata[bot]"
          git config user.email "senile-errata@users.noreply.github.com"

      - name: Add Toolbox Envy to PATH
        uses: EarthmanMuons/toolbox-envy/.github/actions/add-to-path@main
        with:
          include_bins: ${{ inputs.toolbox_envy_bins }}

      - id: tag
        name: Add any missing tags
        run: |
          set -euo pipefail
          tag="$(get-project-version | tag-if-missing)"
          echo "tag=$tag" >>"$GITHUB_OUTPUT"

      - name: Annotate workflow run with new tag
        if: ${{ steps.tag.outputs.tag != '' }}
        run: |
          set -euo pipefail
          {
          echo "### :sparkles: New tag created"
          echo
          echo "- \`${STEPS_TAG_OUTPUTS_TAG}\`"
          } >>"$GITHUB_STEP_SUMMARY"
        env:
          STEPS_TAG_OUTPUTS_TAG: ${{ steps.tag.outputs.tag }}
